DROP TABLE IF EXISTS OBJECT_TAG;
DROP TABLE IF EXISTS OBJECTS;
DROP TABLE IF EXISTS DIMENSIONS;
DROP TABLE IF EXISTS BLOB;
DROP TABLE IF EXISTS TAGS;
DROP TABLE IF EXISTS PLUGINS;
DROP TABLE IF EXISTS CONCEPTS;


CREATE TABLE PLUGINS (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(128) NOT NULL UNIQUE,
  MODULE VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE CONCEPTS (
    ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(128) NOT NULL UNIQUE,
    DESCRIPTION TEXT NOT NULL DEFAULT ''
);

CREATE TABLE TAGS (
  ID SERIAL PRIMARY KEY NOT NULL,
  VALUE VARCHAR(128) NOT NULL,
  DESCRIPTION VARCHAR(128) DEFAULT '',
  MUTABLE BOOL DEFAULT TRUE,
  TYPE INT NOT NULL,
  CONCEPT_ID INT NULL,
  PLUGIN_ID INT NULL,
  FOREIGN KEY(CONCEPT_ID) REFERENCES CONCEPTS(ID),
  FOREIGN KEY(PLUGIN_ID) REFERENCES PLUGINS(ID)
);

CREATE TABLE OBJECTS (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  DIGEST VARCHAR(128) NOT NULL,
  CONSTRAINT OBJECTS_UNIQUE_NAME_DIGEST UNIQUE (NAME, DIGEST)
);

CREATE TABLE DIMENSIONS (
  ROOT_TAG_ID INT NOT NULL,
  NODE_TAG_ID INT NOT NULL,
  LEFT_BORDER INT NOT NULL,
  RIGHT_BORDER INT NOT NULL,
  CONSTRAINT DIMENSIONS_PK PRIMARY KEY(ROOT_TAG_ID, NODE_TAG_ID)
);

CREATE TABLE OBJECT_TAG (
  ID SERIAL PRIMARY KEY NOT NULL,
  OBJECT_ID INT NOT NULL,
  TAG_ID INT NOT NULL,
  PLUGIN_ID INT NULL,
  PLUGIN_SET_ID INT8,
  FOREIGN KEY(TAG_ID) REFERENCES TAGS(ID),
  FOREIGN KEY(OBJECT_ID) REFERENCES OBJECTS(ID),
  FOREIGN KEY(PLUGIN_ID) REFERENCES PLUGINS(ID)
);
