drop table if exists TAGS;
drop table if exists PLUGINS;

CREATE TABLE PLUGINS (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    MODULE VARCHAR(128) NOT NULL
);

CREATE TABLE TAGS (
    ID SERIAL PRIMARY KEY NOT NULL,
    VALUE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(128) DEFAULT '',
    MUTABLE BOOL DEFAULT TRUE,
    TYPE INT NOT NULL,
    PLUGIN_ID INT NULL,
    FOREIGN KEY(PLUGIN_ID) REFERENCES PLUGINS(ID)
);
