#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
cd $SCRIPT_DIR
source utils.sh

ROOT_DIR="$SCRIPT_DIR/.."
VIRTUALENV_DIR_NAME=".venv"
VIRTUALENV_DIR=$SCRIPT_DIR/../$VIRTUALENV_DIR_NAME;
POSTGRES_DATA_DIR="$ROOT_DIR/data";
PROCFILE_LOCATION=$ROOT_DIR/Procfile
cd $ROOT_DIR

function help {
  cout "todo: implement help function"
}

function main {
if [ -d "$VIRTUALENV_DIR" ]; then
  source $VIRTUALENV_DIR/bin/activate
fi
ACTION=$1;

if [ -z "$ACTION" ]; then
  help;
  exit 2;
fi

if [ -f "$SCRIPT_DIR/o3-$ACTION" ]; then
  source $SCRIPT_DIR/o3-$ACTION;
else
  help;
  exit 2;
fi

shift;
COMMAND="cmd_default";

if [ -n "$1" ]; then
  COMMAND="cmd_$1";
  shift;
fi

if isFunction $COMMAND == 1; then
  $COMMAND $@;
else
  echo "Invalid function $COMMAND"
  echo "use \"scripts/objectcube\" help for available commands."
fi
};

main $@;
