#!/bin/bash

function cmd_help {
  echo "showing help for clean."
}

function cmd_default {
  echo "Cleaning environment"
  rm -rf $VIRTUALENV_DIR_NAME
  rm -rf $POSTGRES_DATA_DIR
  rm -rf $PROCFILE_LOCATION
  rm -rf $FILESYSTEM_BLOB_DIR
  rm -rf $COV_DIR
  rm -rf $PEP8_OUTPUT_FILE
  find . -name "*.pyc" | xargs rm
}
