#!/bin/bash
source $SCRIPT_DIR/utils.sh

function cmd_db {
  cout "Initalizing postgresql cluster in $POSTGRES_DATA_DIR"
	mkdir -p $POSTGRES_DATA_DIR;
	initdb -d $POSTGRES_DATA_DIR
}

function cmd_virtualenv {
  echo "Creating virtualenv in $VIRTUALENV_DIR"
  virtualenv $VIRTUALENV_DIR
  source .venv/bin/activate
  pip install -r $ROOT_DIR/requirements.txt
}

function cmd_procfile {
  if [ -f $PROCFILE_LOCATION ]; then
    rm -rf $PROCFILE_LOCATION
  fi

  cat <<EOT >> $PROCFILE_LOCATION
database: postgres -D $POSTGRES_DATA_DIR
EOT
  echo "Procfile created in $PROCFILE_LOCATION"
}

function cmd_schema {
  createdb
  psql $OBJECTCUBE_DB_USER < $ROOT_DIR/schema.sql
}

function cmd_default {
  cmd_virtualenv
  cmd_db
  cmd_startpostgres
  cmd_schema
  cmd_stoppostgres
  cmd_procfile
}

