#!/bin/bash
source $SCRIPT_DIR/utils.sh

function cmd_db {
  cout "Initalizing postgresql cluster in $POSTGRES_DATA_DIR"
	mkdir -p $POSTGRES_DATA_DIR;
	initdb -d $POSTGRES_DATA_DIR --locale C 2<&1 | grep -v '^DEBUG:' || exit 1

  # Check if OBJECTCUBE_DB_PORT is, set if so we add the port to postgresql config
  if [ -z "$OBJECTCUBE_DB_PORT "]; then
    echo "PORT=5432" >> $POSTGRES_DATA_DIR/postgresql.conf
  else
    echo "PORT=$OBJECTCUBE_DB_PORT" >> $POSTGRES_DATA_DIR/postgresql.conf
  fi
}

function cmd_virtualenv {
  echo "Creating virtualenv in $VIRTUALENV_DIR"
  virtualenv $VIRTUALENV_DIR || exit 1
  source .venv/bin/activate
  pip install -r $ROOT_DIR/requirements.txt || exit 1
}

function cmd_procfile {
  if [ -f $PROCFILE_LOCATION ]; then
    rm -rf $PROCFILE_LOCATION
  fi

  cat <<EOT >> $PROCFILE_LOCATION
database: postgres -D $POSTGRES_DATA_DIR
api: gunicorn -w 4 -b 127.0.0.1:4000 api:app
EOT
  echo "Procfile created in $PROCFILE_LOCATION"
}

function cmd_schema {
  createdb
  psql $OBJECTCUBE_DB_USER < $ROOT_DIR/schema.sql
}

function cmd_default {
  cmd_virtualenv
  cmd_db
  cmd_startpostgres
  cmd_schema
  cmd_stoppostgres
  cmd_procfile
}

