#!/bin/bash
function cmd_default {
  echo "Running all tests"
  nosetests -v -s $@
}

function cmd_path {
  echo "Running test by path $@"
  nosetests -v -s $@
}

function cmd_cov {
  nosetests --cover-html-dir $ROOT_DIR/cov --with-coverage --cover-html
}
