#!/bin/bash
function cmd_default {
  echo "Running all tests"
  nosetests -v -s --with-xunit --with-xcoverage $@
}

function cmd_path {
  echo "Running test by path $@"
  nosetests -v -s $@
}

function cmd_cov {
  COV_DIR=$ROOT_DIR/cov
  cout "Running all tests with coverage report in $COV_DIR" 3
  nosetests --cover-html-dir $COV_DIR --with-coverage --cover-html --cover-erase --cover-package=objectcube --cover-branches
}

function cmd_pep8 {
    pep8 objectcube
}
